-- Schemas for each layer (PROJECT_PLAN.md §6.1).
CREATE SCHEMA IF NOT EXISTS seed;
CREATE SCHEMA IF NOT EXISTS stg;
CREATE SCHEMA IF NOT EXISTS clean;
CREATE SCHEMA IF NOT EXISTS core;
CREATE SCHEMA IF NOT EXISTS atlas;
CREATE SCHEMA IF NOT EXISTS night;
CREATE SCHEMA IF NOT EXISTS closure;
CREATE SCHEMA IF NOT EXISTS robust;
CREATE SCHEMA IF NOT EXISTS mart;
